plugins {
    kotlin("jvm")
}

dependencies {
    api(libs.rsmodCoroutines)
    api(libs.rsmodCache)
    api(projects.plugins.typesGenerated)
    implementation(libs.rsmodBuffer)
    implementation(projects.config)
    implementation(projects.game)
    implementation(libs.rsmodEvents)
    implementation(libs.rsmodMap)
    implementation(libs.rsmodScripts)
    implementation(libs.rsmodPathfinder)
    implementation(libs.rsmodProtocol)
    implementation(libs.rsmodJson)
    implementation(libs.rsmodInfo)
    implementation(libs.rsmodTypes)
    implementation(libs.rsmodToml)
    implementation(libs.clikt)
    implementation(libs.inlineLogger)
    implementation(libs.kotlinCoroutinesCore)
    implementation(libs.kotlinScriptRuntime)
    implementation(libs.logback)
    implementation(libs.nettyBuffer)
    implementation(libs.nettyTransport)
    implementation(libs.openrs2Cache)
    implementation(libs.openrs2Crypto)
    implementation(libs.openrs2Buffer)
    testImplementation(projects.plugins.testing.simple)
    integrationImplementation(projects.plugins.testing)
}
